### ISSUE TITLE
IndexedDB vs WebSQL

### ISSUE THREAD

**Issue by ClydeShen** [iuv-dev/routeapp#10]
**Inspect *\* on Chrome to open developer tool, click **Resources** Tab, you will see WebSQL and IndexedDB
- [x] do research about IndexedDB to find out what is IndexedDB 
- [x] do research about WebSQL to find out what is WebSQL
- [x] compare IndexedDB to WebSQL, think about which one is good to store some data.
- [x] compare IndexedDB to WebSQL, think about which one is easy to implement.

**Comment by raira-mioma** [comment]
I just started my research and that's what I've found:
Safari, Chrome 4, and Opera support[7] an alternative mechanism for client-side database storage called Web SQL Database.[8] On November 18, 2010, the W3C announced that the Web SQL database specification has reached an impasse and is no longer being actively worked on.[9] Firefox developers have publicly stated that the lack of WebSQL Database support in Firefox is on purpose, as they believe it is a problematic standard which requires an alternative (hence IndexedDB).[10]

taken from here: https://en.wikipedia.org/wiki/Indexed_Database_API
also here, WebSQL is no longer relevant: https://en.wikipedia.org/wiki/Web_SQL_Database

Thus, I guess, using Web SQL may be not entirely suitable. 

Moreover, here is list of browsers supporting WebSQL: http://caniuse.com/#feat=indexeddb
Browsers supporting IndexedDB: http://caniuse.com/#feat=indexeddb

My suggestion is to think and learn more about pouchDB ( https://pouchdb.com/learn.html - works with AngularJS and cordova!). PouchDB supports all modern browsers, using IndexedDB under the hood and falling back to WebSQL where IndexedDB isn't supported. 

There is also Couchbase: http://developer.couchbase.com/mobile//

CouchDB: http://docs.couchdb.org/en/1.6.1/intro/why.html

PouchDB, Couchbase, CouchDB, IndexedDB are NoSQL, while our old deprecated WebSQL is relational. As far as I can assume, we are looking for a NoSQL database as it will be easier to work with JSON?

As for modern embedded relational databases, we have SQLite and MS SQL Server Compact, IMHO, that's not our case.

And what is more to read:
list of NoSQL databases: http://nosql-database.org/
about CouchDB and PouchDB: https://blog.engineyard.com/2014/an-introduction-to-pouchdb

That's all what I've got for today, need to learn and research more myself. Guess my next attempt will happen on Friday as tomorrow I'm busy at work all day long.

**Comment by raira-mioma** [comment]
Let's rename this issue to: PouchDB vs CouchDB vs Couchbase ^^

**Comment by ClydeShen** [comment]
well done @raira-mioma !! Make sense!! We can close this one and create a new one called PouchDB vs CouchDB vs Couchbase. I will post this to knowledge channel. Thanks~

**Comment by raira-mioma** [comment]
Thank you, Clyde)
