### ISSUE TITLE
JSONP setup

### ISSUE THREAD

**Issue by ClydeShen** [iuv-dev/routeapp#5]
- [x] Understand how JSONP works
- [x] Try to get data from remote server or API
- [x] Try to post data to remote server to create record in table
- [x] Try to delete data on remote server
- [x] Try to update data on remote server

**Comment by GaoxinHuang** [comment]
Hi Clyde, 
I just done one step of task. As for following tasks, I think I will understand google API and use them as an example. so I assign me to google API, is it okay?

**Comment by ClydeShen** [comment]
I already assign map api to you. please check your task list

**Comment by GaoxinHuang** [comment]
Ok, it was assigned by myself.  :) 

then I asked you if it is fine. If not, I will cancel it.

**Comment by ClydeShen** [comment]
That's Ok
